using System;
using System.Data.SqlClient;

public class Product {
    public int productID {get; set;}
    public string name {get; set;}
    public double price {get; set;}
    public ProductDetails details {get; set;}

    public Product(int productID, string name, double price, ProductDetails details) {
        this.productID = productID;
        this.name = name;
        this.price = price;
        this.details = details;
    }

    public bool isOnSale { get { return IsOnSale(); } }
    public double activePrice { get { return GetActivePrice(); } }

    public bool IsOnSale() {
        return GetActivePrice() < this.price;
    }

    public double GetActivePrice() {
        double activePrice = this.price;
        try {
            using (DatabaseConnection database = new DatabaseConnection()) {
                SqlConnection conn = database.OpenConnection();
                //The 'Top 1' part of the SQL command is generated by Google Gemini 3.1 Pro
                // The prompt was "how would I account for multiple discounts on 1 product in this SQL Query:
                // 'SELECT TOP 1 discountAmount 
                //    FROM Sale 
                //    WHERE (productID = @productID OR categoryID = @categoryID)
                //      AND startDate <= GETDATE() AND endDate >= GETDATE()
                //    ORDER BY discountAmount DESC";'"
                // The response was the query used below
                string query = @"
                    SELECT TOP 1 COALESCE(discountAmount, @price * (discountPercentage / 100.0)) 
                    FROM Sale 
                    WHERE (productID = @productID OR categoryID = @categoryID)
                      AND startDate <= GETDATE() AND endDate >= GETDATE()
                    ORDER BY COALESCE(discountAmount, @price * (discountPercentage / 100.0)) DESC";
                using (SqlCommand command = new SqlCommand(query, conn)) {
                    command.Parameters.Add("@productID", System.Data.SqlDbType.Int).Value = this.productID;
                    command.Parameters.Add("@categoryID", System.Data.SqlDbType.Int).Value = this.details.categoryID;
                    command.Parameters.Add("@price", System.Data.SqlDbType.Decimal).Value = this.price;
                    object result = command.ExecuteScalar();
                    if (result != null && result != DBNull.Value) {
                        double discount = Convert.ToDouble(result);
                        if (discount > 0) {
                            activePrice -= discount;
                        }
                    }
                }
            }
        } catch (Exception e) {
            Console.WriteLine(e.Message);
        }
        return Math.Round(activePrice, 2);
    }
}

